name: oidc_macos
description: MacOS implementation of the oidc plugin
version: 0.8.0
repository: https://github.com/Bdaya-Dev/oidc/tree/main/packages/oidc_macos
homepage: https://bdaya-dev.github.io/oidc/
resolution: workspace
publish_to: none
environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.22.0"

flutter:
  plugin:
    implements: oidc
    platforms:
      macos:
        pluginClass: OidcPlugin
        dartPluginClass: OidcMacOS
        swiftPackageManager: true

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth: ^11.0.0
  oidc_core:
    path: ../oidc_core
  oidc_flutter_appauth:
    path: ../oidc_flutter_appauth
  oidc_platform_interface:
    path: ../oidc_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
